# Generated by Django 5.0.4 on 2024-05-08 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["last_name"]},
        ),
    ]
